version: '3.3'

services:
    
  react:
    build:
      context: .
      dockerfile: containers/Dockerfile
    tty: true
    volumes:
      # - ./nextjs-blog:/app
      - ./frontend:/app
    ports:
      - 3000:3000
      - 5173:5173
      - 6006:6006
    # command: sh -c "npm install && npm run dev"
    